version: '1.3.0.{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: 3.5

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - pip install -r src\requirements.txt
  - pip install -r src\requirements-win.txt
  
build_script:
  - cmd: cd src
  - cmd: build-win3-pi.bat


artifacts:
  - path: 'src\*.exe'
  
