version: '1.3.0.{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: 3.5

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - pip install -r src\requirements.txt
  - pip install -r src\requirements-win.txt
  - curl -L -O https://kent.dl.sourceforge.net/project/snap7/1.4.2/snap7-full-1.4.2.7z
  - 7z x snap7-full-1.4.2.7z
  - copy snap7-full-1.4.2\build\bin\win64\snap7.dll c:\windows
  
build_script:
  - cmd: cd src
  - cmd: build-win3-pi.bat


artifacts:
  - path: 'src\*.exe'

deploy:
  provider: BinTray
  username: rpaulo
  api_key:
    secure: CZTTHkcD4MGQO6Gqc5UoPdsDdiyiYfhTI6LI9eqyAzgiIAJlD5U9MctwgICalT6q
  subject: artisan
  repo: artisan-artifacts
  package: artisan
  version: master
  publish: true
  override: true
  explode: false
  
