version: '1.6.0.{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: 3.6
      ARTISAN_VERSION: 1.6.0

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - pip install -r src\requirements.txt
  - pip install -r src\requirements-win.txt
  - curl -L -O https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe
  - curl -L -O https://kent.dl.sourceforge.net/project/snap7/1.4.2/snap7-full-1.4.2.7z
  - 7z x snap7-full-1.4.2.7z
  - copy snap7-full-1.4.2\build\bin\win64\snap7.dll c:\windows
  - curl -L -O https://netix.dl.sourceforge.net/project/libusb-win32/libusb-win32-releases/1.2.6.0/libusb-win32-bin-1.2.6.0.zip
  - 7z x libusb-win32-bin-1.2.6.0.zip
  - copy libusb-win32-bin-1.2.6.0\bin\amd64\libusb0.dll C:\Windows\SysWOW64
  - curl -L -O https://www.phidgets.com/downloads/phidget22/libraries/any/Phidget22Python.zip
  - 7z x Phidget22Python.zip
  - cd Phidget22Python
  - python setup.py install
  - cd ..

build_script:
  - cmd: cd src
  - ps: $GIT_VERSION=git rev-parse --verify --short HEAD
  - ps: gc artisanlib/__init__.py | %{ $_ -replace "__revision__ = '0'", "__revision__ = '$GIT_VERSION'" } | out-file newfile -encoding ascii
  - ps: move -force newfile artisanlib/__init__.py
  - ps: gc setup-install3-pi.nsi | %{ $_ -replace "!define PRODUCT_VERSION.*", "!define PRODUCT_VERSION ""$Env:ARTISAN_VERSION.0""" } | out-file newfile -encoding ascii -force
  - ps: move -force newfile setup-install3-pi.nsi
  - cmd: build-win3-pi.bat
  - cmd: copy ..\LICENSE LICENSE.txt
  - cmd: 7z a artisan-win-%ARTISAN_VERSION%.zip Setup*.exe LICENSE.txt README.txt

artifacts:
  - path: 'src\artisan-*.zip'

deploy:
  provider: BinTray
  username: rpaulo
  api_key:
    secure: CZTTHkcD4MGQO6Gqc5UoPdsDdiyiYfhTI6LI9eqyAzgiIAJlD5U9MctwgICalT6q
  subject: artisan
  repo: artisan-artifacts
  package: artisan
  version: master
  publish: true
  override: true
  explode: false
  on:
    branch: master
  
