language: python

python:
  - "3.6"

install:
  - pip3 install sip pyserial pyqt5 numpy scipy matplotlib pymodbus yoctopuce
  - pip3 install requests gevent gevent-websocket qrcode openpyxl unidecode
  - pip3 install colorspacious
  
script:
  - python3 src/artisan.py
