language: python
matrix:
  include:
  - os: linux
    python: 3.5
  - os: osx
    language: generic
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ruby-dev build-essential
  p7zip-full rpm libusb-1.0; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip libusb qt; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem install fpm; fi
- pip3 install sip pyserial pyqt5 numpy scipy matplotlib pymodbus yoctopuce
- pip3 install requests gevent gevent-websocket qrcode openpyxl unidecode
- pip3 install colorspacious pyusb python-snap7 bottle pyinstaller
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install appnope pyobjc; fi
- curl -L -O https://www.phidgets.com/downloads/phidget22/libraries/any/Phidget22Python.zip
- unzip Phidget22Python.zip
- "(cd Phidget22Python && python3 setup.py install)"
- curl -L -O https://kent.dl.sourceforge.net/project/snap7/1.4.2/snap7-full-1.4.2.7z
- 7za x snap7-full-1.4.2.7z
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd snap7-full-1.4.2/build/unix && make
  -f x86_64_linux.mk all && sudo make -f x86_64_linux.mk install); fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (cd snap7-full-1.4.2/build/osx && make
  -f x86_64_osx.mk all && sudo make -f x86_64_osx.mk LibInstall=/usr/local/lib install);
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L -O https://www.phidgets.com/downloads/phidget22/libraries/macos/Phidget22.dmg;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then hdiutil attach Phidget22.dmg; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo installer -pkg /Volumes/Phidgets22/Phidgets.pkg
  -target / ; fi
script:
- cd src
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build-centos-pi.sh && ./build-linux.sh;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build-mac35-pi.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run --server-args="-screen 0 1024x768x24"
  python artisan.py; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 artisan.py; fi
deploy:
  provider: bintray
  user: rpaulo
  file: .bintray.json
  key:
    secure: wF/zDhgQPkwv642jXY2ZhC+E//UsuRdmoCgrbEakMXMIfFQS6pWplpFbAA31/wi9g6mWe9+BsMOwGmsPcT03bx7AUz3f/hiliM1MxyGcM8Nze6eHGdVIGcShMQk9qLbHIzoc4YjiyEVjKPFwVyiSbEJMzbNvM6UD7quAJcBySHQRVCXC1r0wb5HQ6Tf1e1t0uml8Alzo9XqBH5l20665lqHcKQddHGYpd+UqzcMj/ATjCXACpn1facbt5TidutF3z2uYS+SJbpX2Oe0NIKY+6kNfnVLPzZGUA9ONYIkUvYPApcYo4RbCVgOfvx+ckwwe35j5eGLz8sES6TJkEybFh+qIisxCxESA5P2jt4uW83O3axQa1BaCZu0CriuXO0YT6ccGhsEJvcX9haRT8c9By/KmWfh+5a4Wij8iYCvyE35+LpbKhr1TkywneGyjfVAa+JMyB8WMBtq70aFM018DPMpAi22cE+iWa1Jj4W7H0wHwGWP+wJ3p/XIZYwgEZjGonSUGU173/g7HzlJD/60bc5dqH2AXUHtNzStSKds3frRmKe/bw2Ie8ehBBPpVDqL1r1cp5X/ql4R/z6uH5no/lG9o8hetP3yzxjgzOBd/P6DdClGYaoUzEOHKDvJ/cNRPlxIf0Tk5zG7jYbgoQ3qIKl16V+HNE2XJEOME6AjpYPs=
