language: python

python:
  - "3.6"

install:
  - pip3 install sip pyserial pyqt5 numpy scipy matplotlib pymodbus yoctopuce
  - pip3 install requests gevent gevent-websocket qrcode openpyxl unidecode
  - pip3 install colorspacious pyusb python-snap7 bottle pyinstaller
  - curl -L -O https://www.phidgets.com/downloads/phidget22/libraries/any/Phidget22Python.zip
  - unzip Phidget22Python.zip
  - (cd Phidget22Python && python3 setup.py install)
  
script:
  - cd src
  - xvfb-run --server-args="-screen 0 1024x768x24" python3 artisan.py
  - pyinstaller -D -n artisan -y -c --hidden-import scipy._lib.messagestream --log-level=INFO artisan-linux.spec
