name: Trigger Flathub update

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Flathub update workflow
      uses: peter-evans/repository-dispatch@v4
      with:
        repository: flathub/org.artisan_scope.artisan
        event-type: trigger-workflow
        token: ${{ secrets.TRIGGER_WORKFLOW_TOKEN }}
