name: Pylint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r src/requirements.txt
        pip install -r src/requirements-linux.txt
    - name: Analysing the code with pylint
      run: |
        find src/artisanlib -name '*.py' -exec pylint --disable=C --disable=R --extension-pkg-whitelist=PyQt5 {} \;
        find src/plus -name '*.py' -exec pylint --disable=C --disable=R --extension-pkg-whitelist=PyQt5 {} \;
