name: Pylint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r src/requirements.txt
        pip install -r src/requirements-linux.txt
    - name: Set up reviewdog
      run: |
        mkdir -p "$HOME/bin"
        curl -sfL \
          https://github.com/reviewdog/reviewdog/raw/master/install.sh | \
            sh -s -- -b "$HOME/bin"
        echo "$HOME/bin" >> $GITHUB_PATH
    - name: Analysing the code with pylint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -o pipefail
        for i in $(find src/artisanlib -name '*.py'); do
          pylint --disable=C --disable=R --extension-pkg-whitelist=PyQt5 i | reviewdog -efm="%f:%l:%c: %m" -reporter=github-check
        done
        for i in $(find src/plus -name '*.py'); do
          pylint --disable=C --disable=R --extension-pkg-whitelist=PyQt5 i | reviewdog -efm="%f:%l:%c: %m" -reporter=github-check
        done
