name: Pytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: runner / pytest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies pytest-qt
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements-dev.txt
          pip install -r src/requirements.txt
      - name: Test with pytest
        run: |
          pytest
