name: Pytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: macos-latest # on ubunut the Qt libs are missing: ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
    name: runner / pytest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

#      - name: Install Linux Qt system dependencies
#        if: runner.os == 'Linux'
#        run: |
#          # APT update
#          sudo apt update
#
#          # Install Pyside6 system dependencies
#          # https://doc.qt.io/qt-6/linux-requirements.html
#          sudo apt install -y \
#            libfontconfig1-dev \
#            libfreetype6-dev \
#            libx11-dev \
#            libx11-xcb-dev \
#            libxext-dev \
#            libxfixes-dev \
#            libxi-dev \
#            libxrender-dev \
#            libxkbcommon-dev \
#            libxkbcommon-x11-dev \
#            libatspi2.0-dev \
#            '^libxcb.*-dev'

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements-dev.txt
          pip install -r src/requirements.txt
      - name: Test with pytest
        run: |
          pytest
